swagger: '2.0'
info:
  title: Newsletter API
  description: API for managing newsletters
  version: 1.0.0

paths:
  /api/newsletter:
    post:
      summary: Create a new newsletter
      description: Create a new newsletter
      security:
        - ZeroTrustAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/CreateNewsletterRequest'
      responses:
        '201':
          description: Newsletter created successfully
          schema:
            $ref: '#/definitions/Newsletter'
        '500':
          description: Server error

  /api/newsletter/{newsletterId}/offline:
    put:
      summary: Take a newsletter offline
      description: Mark a newsletter as offline and unsubscribable
      security:
        - ZeroTrustAuth: []
      parameters:
        - name: newsletterId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Newsletter taken offline successfully
        '500':
          description: Server error

  /api/subscribe/confirm:
    post:
      summary: Confirm subscription
      description: Confirm a subscription using the provided token
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/SubscribeConfirmRequest'
      responses:
        '200':
          description: Subscription confirmed successfully
        '400':
          description: Invalid or expired token
        '500':
          description: Server error

  /api/subscribe/cancel:
    post:
      summary: Cancel subscription
      description: Cancel a subscription using the provided token
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/SubscribeCancelRequest'
      responses:
        '200':
          description: Unsubscribed successfully
        '400':
          description: Invalid or expired token
        '500':
          description: Server error

  /api/subscribe/send-confirmation:
    post:
      summary: Send confirmation email
      description: Send a confirmation email with a temporary token
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/SendConfirmationRequest'
      responses:
        '200':
          description: Confirmation email sent successfully
        '500':
          description: Server error

  /api/subscribe/send-cancellation:
    post:
      summary: Send cancellation email
      description: Send a cancellation email with a temporary token
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/SendCancellationRequest'
      responses:
        '200':
          description: Cancellation email sent successfully
        '500':
          description: Server error

  /newsletter/{newsletterId}:
    get:
      summary: Get newsletter details
      description: View newsletter details
      parameters:
        - name: newsletterId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Newsletter details retrieved successfully
          schema:
            $ref: '#/definitions/Newsletter'
        '404':
          description: Newsletter not found
        '500':
          description: Server error

definitions:
  CreateNewsletterRequest:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      logo:
        type: string

  SubscribeConfirmRequest:
    type: object
    properties:
      email:
        type: string
      token:
        type: string

  SubscribeCancelRequest:
    type: object
    properties:
      email:
        type: string
      token:
        type: string

  SendConfirmationRequest:
    type: object
    properties:
      email:
        type: string
      newsletterId:
        type: string

  SendCancellationRequest:
    type: object
    properties:
      email:
        type: string
      newsletterId:
        type: string

  Newsletter:
    type: object
    properties:
      id:
        type: string
        format: uuid
      title:
        type: string
      description:
        type: string
      logo:
        type: string
      subscriberCount:
        type: integer
      subscribable:
        type: boolean

securityDefinitions:
  ZeroTrustAuth:
    type: apiKey
    in: header
    name: Authorization
