name = "i365-letter-drop"
node_compat = true
compatibility_date = "2023-12-01"

# [vars]
# ALLOWED_EMAILS = "a@b.com,c@d.com"

services = [
  { binding = "NOTIFICATION", service = "my-invest-notification", environment = "production" }
]

[[queues.producers]]
binding = "QUEUE"
queue = "i365-letter-drop"

[[queues.consumers]]
queue = "i365-letter-drop"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 10
dead_letter_queue = "i365-letter-drop-dlq"

[[kv_namespaces]]
binding = "KV"
id = "58ce70465f394f369376c6a3af439d77"

[[r2_buckets]]
binding = "R2"
bucket_name = "i365-letter-drop"

[[d1_databases]]
binding = "DB"
database_name = "i365-letter-drop-prod"
database_id = "7ba535ae-d6c7-4570-854d-2483970acd10"

# [ai]
# binding = "AI"